export enum SettingActions {

    // fetch departement
    LAB_LABO_SETTING_ADD_NEW_DEPARTEMENT = "@@setting/LAB_LABO_SETTING_ADD_NEW_DEPARTEMENT",
    LAB_LABO_SETTING_ADD_NEW_DEPARTEMENT_ERROR = "@@setting/LAB_LABO_SETTING_ADD_NEW_DEPARTEMENT_ERROR",
    LAB_LABO_SETTING_ADD_NEW_DEPARTEMENT_SUCCESS = "@@setting/LAB_LABO_SETTING_ADD_NEW_DEPARTEMENT_SUCCESS",

    // add departement
    LAB_LABO_SETTING_LIST_DEPARTEMENT = "@@setting/LAB_LABO_SETTING_LIST_DEPARTEMENT",
    LAB_LABO_SETTING_LIST_DEPARTEMENT_ERROR = "@@setting/LAB_LABO_SETTING_LIST_DEPARTEMENT_ERROR",
    LAB_LABO_SETTING_LIST_DEPARTEMENT_SUCCESS = "@@setting/LAB_LABO_SETTING_LIST_DEPARTEMENT_SUCCESS",

    // fetch jf
    LAB_LABO_SETTING_LIST_HOLIDAY = "@@setting/LAB_LABO_SETTING_LIST_HOLIDAY",
    LAB_LABO_SETTING_LIST_HOLIDAY_ERROR = "@@setting/LAB_LABO_SETTING_LIST_HOLIDAY_ERROR",
    LAB_LABO_SETTING_LIST_HOLIDAY_SUCCESS = "@@setting/LAB_LABO_SETTING_LIST_HOLIDAY_SUCCESS",

    // add jf
    LAB_LABO_SETTING_ADD_NEW_HOLIDAY = "@@setting/LAB_LABO_SETTING_ADD_NEW_HOLIDAY",
    LAB_LABO_SETTING_ADD_NEW_HOLIDAY_ERROR = "@@setting/LAB_LABO_SETTING_ADD_NEW_HOLIDAY_ERROR",
    LAB_LABO_SETTING_ADD_NEW_HOLIDAY_SUCCESS = "@@setting/LAB_LABO_SETTING_ADD_NEW_HOLIDAY_SUCCESS",

    // fetch CONGER
    LAB_LABO_SETTING_LIST_LEAVE = "@@setting/LAB_LABO_SETTING_LIST_LEAVE",
    LAB_LABO_SETTING_LIST_LEAVE_ERROR = "@@setting/LAB_LABO_SETTING_LIST_LEAVE_ERROR",
    LAB_LABO_SETTING_LIST_LEAVE_SUCCESS = "@@setting/LAB_LABO_SETTING_LIST_LEAVE_SUCCESS",

    // add CONGER
    LAB_LABO_SETTING_ADD_NEW_LEAVE = "@@setting/LAB_LABO_SETTING_ADD_NEW_LEAVE",
    LAB_LABO_SETTING_ADD_NEW_LEAVE_ERROR = "@@setting/LAB_LABO_SETTING_ADD_NEW_LEAVE_ERROR",
    LAB_LABO_SETTING_ADD_NEW_LEAVE_SUCCESS = "@@setting/LAB_LABO_SETTING_ADD_NEW_LEAVE_SUCCESS",

    // fetch automate
    LAB_LABO_SETTING_LIST_AUTOMATE = "@@setting/LAB_LABO_SETTING_LIST_AUTOMATE",
    LAB_LABO_SETTING_LIST_AUTOMATE_ERROR = "@@setting/LAB_LABO_SETTING_LIST_AUTOMATE_ERROR",
    LAB_LABO_SETTING_LIST_AUTOMATE_SUCCESS = "@@setting/LAB_LABO_SETTING_LIST_AUTOMATE_SUCCESS",

    // add automate
    LAB_LABO_SETTING_ADD_NEW_AUTOMATE = "@@setting/LAB_LABO_SETTING_ADD_NEW_AUTOMATE",
    LAB_LABO_SETTING_ADD_NEW_AUTOMATE_ERROR = "@@setting/LAB_LABO_SETTING_ADD_NEW_AUTOMATE_ERROR",
    LAB_LABO_SETTING_ADD_NEW_AUTOMATE_SUCCESS = "@@setting/LAB_LABO_SETTING_ADD_NEW_AUTOMATE_SUCCESS",

}