export enum StaffActions {
    // add employer
    ADD_EMPLOYER = '@@staff/ADD_EMPLOYER',
    ADD_EMPLOYER_ERROR = '@@staff/ADD_EMPLOYER_ERROR',
    ADD_EMPLOYER_SUCCESS = '@@staff/ADD_EMPLOYER_SUCCESS',

    // list staff
    LIST_ALL_EMPLOYERS = '@@staff/LIST_ALL_EMPLOYERS',
    LIST_ALL_EMPLOYERS_ERROR = '@@staff/LIST_ALL_EMPLOYERS_ERROR',
    LIST_ALL_EMPLOYERS_SUCCESS = '@@staff/LIST_ALL_EMPLOYERS_SUCCESS',

}
